import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { ThemeProvider } from "@/components/theme-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "../../next-auth.config";
import { useAxiosAuth } from "@/hooks/useAxiosAuth";
import { TokenHandler } from "@/components/TokenHandler";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Shoqan Education",
  description: "Generated by create next app",
  // robots: {
  //   index: false, follow: false,
  // },
  verification: {
    google: "kUeM3WNtUXMoBtgpz2HAknDwHEkJVK1DtE46N8dO7w",
  },
  // other: {
  //   'google-site-verification': 'kUeM3WNtUXMoBtgpz2HAknDwHEkJVK1DtE46N8dO7w'
  // }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (!session) {
    // redirect("/auth/signin");
  }

  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head>
        <meta
          name="google-site-verification"
          content="7CtjbVRhzjTYn084fvcZ0MpIiiZDZ1keT8-buUTDWyo"
        />
      </head> */}
      <body>
        <Providers session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <TokenHandler />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
